// Question selection + scoring helpers.
import ALL from "../data/questions.json";
import { DOMAINS, EXAM } from "../data/curriculum.js";

export const allQuestions = ALL;

// --- FREE TIER: 23 questions that prove quality and create FOMO ---
// Covers all 5 domains + 3 scenarios. Deliberately missing: Domain 4, 85 scenarios, mock exams, curriculum.
export const FREE_IDS = new Set([
  // Domain 1: Agentic Architecture & Orchestration (6)
  "GH-07-002", "GH-09-043", "GH-07-004", "GH-09-041", "GH-07-003", "GH-09-042",
  // Domain 2: Tool Design & MCP (4)
  "GH-08-013", "GH-08-010", "GH-08-014", "GH-08-002",
  // Domain 3: Claude Code Configuration (6)
  "GH-05-020", "GH-03-001", "GH-05-021", "GH-05-019", "GH-02-001", "GH-06-018",
  // Domain 5: Conversational AI Patterns (4)
  "SG-070", "SG-075", "SG-066", "SG-065",
  // Scenario questions (3 — one each from 3 scenarios)
  "SG-057", "SG-007", "SG-016",
]);

export const freeQuestions = ALL.filter((q) => FREE_IDS.has(q.id));

// --- LICENSE / ACCESS CODE SYSTEM ---
// Simple obfuscated check — not bulletproof (client-side), but deters casual sharing.
// When Lenise sells via Gumroad, she distributes these codes.
function simpleHash(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) - h + str.charCodeAt(i)) | 0;
  }
  return h;
}

const VALID_HASHES = new Set([
  // SHAEP-XXXXX format codes. Hashed so they're not visible in source.
  // Pre-loaded launch codes (generated by generate-access-codes.js)
  simpleHash("SAEP-LAUNCH-2026"),
  simpleHash("SAEP-FOUNDERS-ACCESS"),
  simpleHash("SAEP-STUDY-PASS"),
  58178931,     // SAEP-65089OSU
  894277178,    // SAEP-6508VCJX-1
  349813980,    // SAEP-6508CBXU-2
  424579781,    // SAEP-6508F6WK-3
  538555343,    // SAEP-6508IUEF-4
  -135213288,   // SAEP-65082DRU-5
  412644164,    // SAEP-6508EHYV-6
  -175402306,   // SAEP-650818BT-7
  586741809,    // SAEP-6508KKJU-8
  712521334,    // SAEP-6508OWQ8-9
  -829444064,   // SAEP-6509UZJ5-10
  231701965,    // SAEP-65090JFP-11
  1410479298,   // SAEP-6509NV0X-12
  -189687032,   // SAEP-6509CG2Y-13
  -471155921,   // SAEP-65094KUC-14
  -1988054058,  // SAEP-65093673-15
  -1388147994,  // SAEP-6509G77W-16
  685189965,    // SAEP-6509X2FV-17
  -2118181143,  // SAEP-65092PE6-18
  701335515,    // SAEP-6509S88Q-19
]);

export function isValidLicense(code) {
  if (!code) return false;
  const clean = code.trim().toUpperCase();
  return VALID_HASHES.has(simpleHash(clean));
}

export function isLicensed() {
  try {
    return localStorage.getItem("saep_license") === "active";
  } catch { return false; }
}

export function activateLicense(code) {
  if (isValidLicense(code)) {
    localStorage.setItem("saep_license", "active");
    return true;
  }
  return false;
}

export function deactivateLicense() {
  localStorage.removeItem("saep_license");
}

export function isFreeMode() {
  return !isLicensed();
}

// --- QUESTION SELECTION ---

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Pick questions by spec, lightly preferring unseen / previously-missed ones.
// In free mode, only serves from FREE_IDS.
export function pickQuestions(spec, state, count) {
  const n = count || spec.count || 8;
  const freeMode = isFreeMode();
  let pool = ALL.filter((q) => !freeMode || FREE_IDS.has(q.id));
  if (spec.domain) pool = pool.filter((q) => (q.domains || []).includes(spec.domain));
  else if (spec.scenario) pool = pool.filter((q) => q.scenario === spec.scenario);
  else if (spec.weak) {
    const weakest = weakestDomain(state);
    pool = pool.filter((q) => (q.domains || []).includes(weakest));
  }
  // mixed / exam => whole pool (filtered by free mode above)
  const h = state?.qHistory || {};
  const score = (q) => {
    const rec = h[q.id];
    if (!rec) return 0;                  // unseen first
    if (rec.lastCorrect === false) return 1; // then previously missed
    return 2 + rec.attempts;             // mastered later
  };
  const ranked = shuffle(pool).sort((a, b) => score(a) - score(b));
  return ranked.slice(0, Math.min(n, ranked.length));
}

// Build free assessment (23 questions, shuffled)
export function buildFreeAssessment() {
  return shuffle([...freeQuestions]);
}

// Weighted exam: sample 60 across domains by exam weight. Paid only.
export function buildExam(state) {
  if (isFreeMode()) return []; // safety: should never be called in free mode
  const target = {};
  let remaining = EXAM.questions;
  const weights = Object.entries(DOMAINS);
  weights.forEach(([d, info], i) => {
    const c = i === weights.length - 1 ? remaining : Math.round((info.weight / 100) * EXAM.questions);
    target[d] = c; remaining -= c;
  });
  const out = [];
  const used = new Set();
  for (const [d, c] of Object.entries(target)) {
    const pool = shuffle(ALL.filter((q) => (q.domains || []).includes(Number(d)) && !used.has(q.id)));
    pool.slice(0, c).forEach((q) => { out.push(q); used.add(q.id); });
  }
  // backfill if short
  if (out.length < EXAM.questions) {
    shuffle(ALL.filter((q) => !used.has(q.id))).slice(0, EXAM.questions - out.length)
      .forEach((q) => { out.push(q); used.add(q.id); });
  }
  return shuffle(out);
}

// Convert raw % to the exam's 100–1000 scale (720 ≈ ~70%). Linear, clamped.
export function toScaled(correct, total) {
  if (!total) return 0;
  const pct = correct / total;
  const scaled = Math.round(100 + pct * 900);
  return Math.max(100, Math.min(1000, scaled));
}

export function weakestDomain(state) {
  const s = state?.domainStats || {};
  let worst = 1, worstRate = 2;
  for (let d = 1; d <= 5; d++) {
    const st = s[d];
    const rate = st && st.seen ? st.correct / st.seen : -1; // unseen = weakest
    if (rate < worstRate) { worstRate = rate; worst = d; }
  }
  return worst;
}

export function domainAccuracy(state) {
  const s = state?.domainStats || {};
  const out = {};
  for (let d = 1; d <= 5; d++) {
    const st = s[d];
    out[d] = st && st.seen ? Math.round((st.correct / st.seen) * 100) : null;
  }
  return out;
}

// Record a single answered question into state (mutates a copy, returns it).
export function recordAnswer(state, q, isCorrect) {
  const next = { ...state, domainStats: { ...state.domainStats }, qHistory: { ...state.qHistory } };
  for (const d of q.domains || []) {
    if (d === 0) continue;
    const cur = next.domainStats[d] || { seen: 0, correct: 0 };
    next.domainStats[d] = { seen: cur.seen + 1, correct: cur.correct + (isCorrect ? 1 : 0) };
  }
  const rec = next.qHistory[q.id] || { attempts: 0, lastCorrect: null };
  next.qHistory[q.id] = { attempts: rec.attempts + 1, lastCorrect: isCorrect };
  return next;
}
